[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
bytecode_hash = "none"
optimizer_runs = 1000000
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solmate/=lib/solmate/src/',
]

[profile.default.fuzz]
runs = 40

[profile.intense.fuzz]
runs = 1_000
max_test_rejects = 1_000_000

[profile.optimized]
out = "optimized-out"
via_ir = true

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

